### ISSUE TITLE
Add built-in functions "not contains"

### ISSUE THREAD

**Issue by vavasilva** [jmespath/jmespath.site#105]
Is it possible add a  built-in function "not contains"?

**Comment by springcomp** [comment]
You can emulate this combining the `contains()` function with a `not-expression`:

`` search( [? !contains(@, `2`)][], [[1, 3, 5], [2, 4, 6], [1, 2, 3]]) -> [1, 3, 5] ``

**Comment by vavarodrigues** [comment]
Perfect, thank you @springcomp!
