### ISSUE TITLE
Add a map() function

### ISSUE THREAD

**Issue by jamesls** [jmespath/jmespath.site#15]
Not sure this warrants a full JEP, but I think it would be useful to have a `map()` function that takes two args, an expref and input data, and applies the expression ever every element in the second arg:

```
Signature:

array[any] map(expression->any->any, array[any])

Example:

map(&foo, `[{"foo": "a"}, {"foo": "b"}, {"foo": "c"}]`) -> ["a", "b", "c"]
```

At first, this might seem the exact same as a projection, so the example above could just be `[*].foo`.

However, there's a key difference: **you will always know the size of the output array**.  That is, given an array of length N, `map` will **always** return back an array of length N.  Projections will not include any element in the final list whose value is `null`.  So really `[*].bar` is saying "for each element in the list, if there's a bar value, and it's not `null`, include it in the returned list.

The above feature (that is always producing an output of length N elements) has been requested several times before, most recently [here](http://stackoverflow.com/questions/32612193/jmespath-nested-or-statement).

The second is the ability to be more explicit with regard to what expression is being evaluated against each element.  `map()` clearly takes two arguments, the first is the expression, the second is the input array.  Sometimes, it's not possible to override the parser's precedence, for example the expression `[*][]`, where conceptually you wan to say "try to flatten each element in the input array" is not possible because flatten has such a weak binding, the parser interprets `Identity()` for the RHS of the expression `[*][]`. This is discussed here: https://github.com/jmespath/jmespath.py/issues/92.  This would be much more explicit by just saying `map(&[], myinput)`.

EDIT: More examples:

```
# Notice how there's a `None` value in the 3rd and 4th element
>>> jmespath.search('map(&foo, array)', {'array': [{'foo': 'a'}, {'foo': 'b'}, {}, [], {'foo': 'f'}]})
['a', 'b', None, None, 'f']

# What was requested in jmespath/jmespath.py#92:
>>> search('map(&[], @)', [[1, 2, 3, [4]], [5, 6, 7, [8, 9]]])
[[1, 2, 3, 4], [5, 6, 7, 8, 9]]

# From stackoverflow (http://stackoverflow.com/questions/32612193/jmespath-nested-or-statement):
>>> stackoverflow = [
...     {
...         'foo': {'bar': 'yes1'}
...     },
...     {
...         'foo': {'bar': 'yes2'}
...     },
...     {
...         'foo1': {'bar': 'no'}
...     }
... ]
>>> search('map(&foo.bar, [*])', stackoverflow)
['yes1', 'yes2', None]
```

**Comment by mtdowling** [comment]
I like it

**Comment by jamesls** [comment]
Accepted, I'll update the docs and jmespath.test.

**Comment by jamesls** [comment]
Closed via: https://github.com/jmespath/jmespath.site/commit/436baafe3edfeeb488a0b11dfc130df747ddc8ed

**Comment by joshlk** [comment]
Thanks!
