### ISSUE TITLE
Missing expression types in expression definition

### ISSUE THREAD

**Issue by bjorne** [jmespath/jmespath.site#19]
The grammar does not include `and-expression`, `not-expression` or `paren-expression` under the definition of `expression`. Since there is no mention of these elsewhere in the specification, I suspect that they should indeed be considered `expression`s. In other words, I'm missing a line in the grammar equivalent to the following:

```
expression        =/ and-expression / not-expression / paren-expression
```

Alternatively, I would expect the specification to mention how and where these expression types are valid. It may also be the case that I have misunderstood something fundamentally or am completely blind.

**Comment by jamesls** [comment]
Good catch, thanks for letting me know.  Those rules should just be added under the definition of expression as you suggested.  I'll get that updated.
