### ISSUE TITLE
Specification typos (``)

### ISSUE THREAD

**Issue by jrotenstein** [jmespath/jmespath.site#33]
Page: http://jmespath.org/specification.html

These appear to be typos in the `ends_with` documentation:

    ends_with(@, ``baz)``
    ends_with(@, ``foo)``
    ends_with(@, ``z)``

Also, in the `join` documentation:

    join(``, @)``

**Comment by betelgeuse** [comment]
Pull request #48 seems to have fixes for this.

**Comment by jamesls** [comment]
Closing out old issue, this has been fixed.
