### ISSUE TITLE
Add definition of JMESPath acronym

### ISSUE THREAD

**Issue by Daniel-at-github** [jmespath/jmespath.site#38]
Add definition of JMESPath acronym, maybe in an About section

I guess the Acronym is something like this

Letter | Meaning
--- | --
J | Javascript
M | ???
E | ???
S | ???
Path | Path

**Comment by rog555** [comment]
I always assumed it was related to JaMES Saryerwinnie :-)
or maybe something like Json Modular/Meta Expression Syntax (random guesses)

**Comment by craiginscotland** [comment]
wow, can't believe this is still outstanding!

**Comment by gromenauer** [comment]
James Moriarty Eobard Saryerwinnie Path? (Hope not :stuck_out_tongue: )

**Comment by sherif-botros** [comment]
http://jmespath.org/contents.html 
MESPath (JSON Matching Expression paths) is a query language for search JSON documents

**Comment by Daniel-at-github** [comment]
Thanks @sherif-botros
