### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by innovate-invent** [jmespath/jmespath.site#65]
Is this project dead?
There seem to be several rather important PRs pending for years.
https://github.com/jmespath/jmespath.site/pull/6
https://github.com/jmespath/jmespath.site/pull/21
https://github.com/jmespath/jmespath.py/issues/110

**Comment by springcomp** [comment]
Shouldn’t the community do something about this?

The [http://jmespath.org/](http://jmespath.org/) domain name is set to expire on november the 11th. And the various repositories have not seen any activities from James for more than three years now.

At the risk of coming accross badly, I, for one, would be willing to maintain a `jmespath.jep` or `jmespath.spec` repository as explained [here](https://github.com/jmespath/jmespath.test/issues/1#issuecomment-173660773) and [there](https://github.com/jmespath/jmespath.site/pull/2#issuecomment-67879608).

If that sounds good, I would include various proposals and PRs such as those listed above.

As the co-author of [JmesPath.Net] I would like to see this through. However, I cannot commit to maintain the site or the various other language implementations.

Would my proposal be welcome by the community. Am I not breaking some FOSS etiquette I'm not aware of? I understand that the author of an open source project has no obligation. I, myself, sit on PRs or issues in my own repos for months sometimes. But I think Jmespath is a great spec and should be maintained and welcome improvements from the community.

**Comment by innovate-invent** [comment]
@jamesls Are you still alive?
I am only half joking :yum:

**Comment by myrdd** [comment]
@springcomp imho it would be at least nice to have a version of the website (`jmespath.site`) with all the issues fixed. if you decide to do so—i.e. to fork the website and publish it—I recommend you to put a disclaimer on the site stating the project status with a link where to discuss the current status (e.g. this issue).

**Comment by gwerbin** [comment]
@springcomp I think that's reasonable.

Anyone interested in keeping this project alive could also help by putting out a call to other developers they know who might be able to help.

**Comment by myrdd** [comment]
> Anyone interested in keeping this project alive could also help by putting out a call to other developers they know who might be able to help.

good idea. maybe contact mayor dependants—I know of Ansible (its [`json_query`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter) jinja templating filter) and the [AWS cli](https://docs.aws.amazon.com/cli/latest/reference/index.html)—as well as package maintainers (most importantly, the python implementation, see https://repology.org/project/python:jmespath/versions).

**Comment by chris-armstrong** [comment]
FWIW, we (GorillaStack) are maintaining a jmespath.js fork and a copy of the site:

https://github.com/gorillastack/jmespath.js
https://github.com/gorillastack/jmespath.site (published to https://gorillastack-jmespath.netlify.com)

I would love somewhere to propose specification improvements. I'm making additions and improvements and bugfixes to the jmespath fork, but it would be great to formalise the new functions and syntactic additions as proposals so other forks can stay up to date.

**Comment by chris-armstrong** [comment]
Update: 
* I've linked to this issue on the [web site](https://gorillastack-jmespath.netlify.com/) and [jmespath.js](https://github.com/gorillastack/jmespath.js) forks
* Added contribution guidelines for our [jmespath.js](https://github.com/gorillastack/jmespath.js) fork

I'm also starting to create proposals for changes - please see [the proposals page](https://gorillastack-jmespath.netlify.com/proposals.html)

**Comment by henning** [comment]
I'd be interested to help with advancing the python implementation.

**Comment by chris-armstrong** [comment]
I've also forked the jmespath.test repository, upgraded its test infrastructure and schema, and added the compliance tests for GorillaStack's spec additions (split() function and to_json()/parse_json() proposals (both in our jmespath.js fork)
https://github.com/GorillaStack/jmespath.test
(see https://gorillastack-jmespath.netlify.com/proposals for descriptions of those proposals)

**Comment by springcomp** [comment]
@chris-armstrong Wow, that is impressive, thank you for your efforts.

I unfortunately never got the time to follow through my proposal made back in August but I'm glad the project still generates enthusiasm and actual work.

I will add a proposal for an [iff](https://github.com/springcomp/JmesPath.Net.Functions/wiki/iff) function that I made back then to your proposals page.

I like the various string and JSON manipulation functions and will try and implement them in the .net port.

**Comment by darrenmothersele** [comment]
I've been using a modified version of jmespath.js on a project for a while now. I have uploaded a cleaned up version of this fork:
https://github.com/daz-is/jmespath.js

Rather than adding functions to the spec, I've added a `decorate` function that allows the consumer of the library to add their own functions (along with type signatures for type checking).

An example of extending it with functions is in:
https://github.com/daz-is/jmespath-plus

It also allows caching of parsed expressions, so that they can be reused and evaluated against multiple inputs.

I also added a `$` symbol for accessing back to the root of the input when nested within an expression.

**Comment by jamesls** [comment]
Hey everyone, sorry for not being present in this project for a while, but I'm still alive and I'll have more time to allocate working on this project now.  Other the next few weeks I'll be going through the various issues and pull requests to get everything triaged and updated.

One of the immediate things I'd like to do is to start up development of the JMESPath spec again.  I initially wanted a freeze on the language for a while to allow for the various language implementation and tooling to stabilize but I think we're way past that point now.  I don't think the jmespath.site should be the place for tracking proposals to the language, so I'm all in favor of creating a new jmespath.spec repo where we can propose new ideas.  I'll get that set up in the next few days.

**Comment by jilvin** [comment]
@jamesls Can you consider publishing the change to the license field in package.json to npm? Shows license: none at the moment at https://www.npmjs.com/package/jmespath . Will help to work with other license checking tools too.

PS: Renaming LICENSE.txt to LICENSE would be great too.

**Comment by glenveegee** [comment]
Hi all,

I hope no-one minds but I've rewritten the entire jmespath.js repo in typescript.

https://github.com/nanoporetech/jmespath-ts

If you find it a worthy replacement for the current `jmespath.js` package you're welcome to use it. we'll hold off publishing it to npm in case there's some feedback about adopting this version. Otherwise I'd be happy to publish it under a different moniker.

Two final points:

1. I haven't deviated from the spec in any way apart from adding `\r` as a skip character
2. For those that like to add custom functions of their own there is a generic mechanism to do that (see the last few unit tests in `jmespath.spec.js`) which also handles input argument validation.

**Comment by jameswilson** [comment]
@jamesls what is involved with getting jmespath.spec repository setup?

**Comment by jamesls** [comment]
I created the repo a while back but I need to port the existing proposals over to the site, was converting the existing proposals over to markdown just to make it easier for people to contribute: https://github.com/jmespath/jmespath.jep

**Comment by jameswilson** [comment]
Ah I entirely missed that repository. when I scanned the list here  https://github.com/jmespath I guess due to the naming of the extension on the repository I didn't recognize "jep" and figured it was another programming language or something.

**Comment by innovate-invent** [comment]
@jamesls with the move to the jmespath.jep repository, does that invalidate the already well written PRs pending in the jmespath.site repository?

The contributions mentioned in my original post are critical to JMESPaths future. What is their status?
