### ISSUE TITLE
Use HTTPS for site

### ISSUE THREAD

**Issue by impredicative** [jmespath/jmespath.site#68]
Please use https for the website. It's embarrassing to use http these days. Obviously you can get a free cert from https://letsencrypt.org/ .

Also, the repo hasn't been updated in over a year even though there are so many Issues and PRs. If it's dead, please admit it and say so.

**Comment by jamesls** [comment]
Still alive!  See https://github.com/jmespath/jmespath.site/issues/65#issuecomment-592613602.

You're right, this should be using HTTPS.  I'm working on this now.
