### ISSUE TITLE
Is there a way to get the map result with 'relative path' like *..c ?

### ISSUE THREAD

**Issue by ClericPy** [jmespath/jmespath.site#74]
input:
{"a": {"b": {"c": {"d": "value"}}}}
path:
*..c
expect:
{"d": "value"}

**Comment by darrenmothersele** [comment]
This works for the example you've given...
```
values(@)[0].values(@)[0].values(@)[0]
```

**Comment by ClericPy** [comment]
> This works for the example you've given...
> 
> ```
> values(@)[0].values(@)[0].values(@)[0]
> ```

Thanks for answering, but the relative path means that I don't know how many blocks in the given nested dict, so I wonder if there is a way to do like the objectpath do.

```python
import objectpath

raw = {
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
        "X-Amzn-Trace-Id": "Root=1-5e67a051-171e2874180dc5964fb7884d"
    },
    "origin": "47.104.199.113",
    "url": "http://httpbin.org/get"
}
tree = objectpath.Tree(raw)
result = [i for i in tree.execute('$..Accept')]
print(result)
# ['*/*']
```

**Comment by darrenmothersele** [comment]
Ah, I see. As far as I know, recursive descent is not possible in JMESPath

**Comment by ClericPy** [comment]
@darrenmothersele 

Yes, I read the doc/source code in a while but not found that feature, so it may not be the purpose of JMESPath.

JMESPath is very fast, and the implementation didn't contains a recursive parsing usage, this issue is just want to ensure that.

Close issue, thank all the same.

**Comment by springcomp** [comment]
@ClericPy We want to [propose this feature to JMESPath](https://github.com/jmespath/jmespath.jep/issues/31) and will include this in the [next iteration for JMESPath Community](https://github.com/jmespath-community/jmespath.spec/discussions/151).
