### ISSUE TITLE
More examples for function `contains`

### ISSUE THREAD

**Issue by RichardBronosky** [jmespath/jmespath.site#8]
The documentation at http://jmespath.org/specification.html#contains demonstrates partial string matching on string input. The array input examples use only arrays of single character strings. This makes it unclear as to whether partial matching is done. I reality, partial matching is not performed against arrays. I'm not complaining about the matching. It makes sense to do it this way if you consider string input to be a "character array".

I'm providing a patch to improve clarity.

**Comment by jamesls** [comment]
Fixed via #9
