### ISSUE TITLE
jq's select equivalent for jmespath

### ISSUE THREAD

**Issue by feyzee** [jmespath/jmespath.site#87]
I'm looking for jq's select equivalent in jmespath.

I've the following json

```json
[
  {
    "event_type": "send",
    "attributes": {
      "send_status": "SUCCESS",
      "activity_type": "EMAIL"
    }
  },
  {
    "event_type": "click",
    "attributes": {
      "send_status": "THROTTLED",
      "activity_type": "EMAIL"
    }
  },
  {
    "event_type": "send",
    "attributes": {
      "send_status": "DELIVERED",
      "activity_type": "EMAIL"
    }
  }
]
```

following is the query I've used in jq for filtering -

`cat file.json | jq 'select(.event_type=="click") | {status: .attributes.send_status, type: .attributes.activity_type}'`

here jq filters out objects if event_type is not "click". how to achieve this in jmespath?

**Comment by b-enoit-be** [comment]
Here is the JMESPath equivalent:

```
[?event_type=='click'].{status: attributes.send_status, type: attributes.activity_type}
```
